name: CI/CD hdev_client to AWS S3

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: AWS IAM Setting
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Npm install babel
        run: |
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
      - name: Npm Install
        run: |
          npm install
      - name: Npm Build
        run: |
          npm run build
        env:
          CI: false

      - name: Upload on S3
        run: aws s3 sync build/ s3://hackathon-front --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
